import { Router } from "express";
import { NotificationController } from "../controllers/NotificationController";
const router = Router(), controller = new NotificationController();
router.get("/settings/:shop", controller.getSettings.bind(controller));
router.put("/settings/:shop", controller.saveSettings.bind(controller));
router.get("/domains/:shop", controller.getDomains.bind(controller));
router.post("/domains/:shop/setup", controller.setupDomain.bind(controller));
router.post("/domains/:shop/verify", controller.verifyDomain.bind(controller));
router.post("/domains/:shop/refresh", controller.refreshDomain.bind(controller));
router.post("/test/:shop", controller.test.bind(controller));
export default router;
