import assert from "node:assert/strict";
import test from "node:test";
import { RetryFailureAction, RetryJobStatus, RetryKind, TeamNotificationFrequency } from "@prisma/client";
import { RetryEngineService, RetryMetrics } from "../RetryEngineService";

const now = new Date("2026-08-20T12:00:00.000Z");
process.env.SHOPIFY_APP_URL = "https://app.test";
process.env.SHOPIFY_APP_API_KEY = "secret";
const metrics = (): RetryMetrics => ({ found: 0, claimed: 0, completed: 0, rescheduled: 0, failed: 0, skipped: 0 });
function fixture(overrides: Record<string, any> = {}) {
  const job: any = { id: "job-1", shopId: "shop-1", subscriptionId: "sub-1", cycleId: "cycle-1", kind: RetryKind.INVENTORY, attemptNumber: 0, maxRetries: 2, status: RetryJobStatus.PENDING, scheduledAt: now, claimedAt: null, leaseExpiresAt: null, completedAt: null, idempotencyKey: "aps:cycle-1:inventory:0", reconciliationCount: 0, maxReconciliations: 3, firstUncertainAt: null, lastReconciledAt: null, reconciliationDeadlineAt: null, externalAttemptId: null, cycle: { id: "cycle-1", shopId: "shop-1", subscriptionId: "sub-1", billingCycleAt: now, status: "pending", finalAction: null, finalActionStatus: "none", finalActionLeaseExpiresAt: null, nextBillingAdvanced: false }, subscription: { id: "sub-1", shopId: "shop-1", gateway: "shopify", status: "active", shopifyContractId: "gid://shopify/SubscriptionContract/1", billingInterval: "month", billingIntervalCount: 1, lastPaymentStatus: null, shop: { domain: "one.myshopify.com" }, contractLines: [{ shopifyVariantId: "gid://shopify/ProductVariant/1", quantity: 1 }] }, ...overrides };
  const jobs = new Map([[job.id, job]]), cycles = new Map([[job.cycle.id, job.cycle]]), attempts = new Map<string, any>(), orders = new Map<string, any>(), outbox = new Map<string, any>(); let transactionCount = 0, externalCalls = 0;
  const settings: any = { paymentRetryAttempts: 2, paymentRetryDays: 2, paymentFailureAction: RetryFailureAction.PAUSE_AND_NOTIFY, inventoryRetryAttempts: 2, inventoryRetryDays: 1, inventoryFailureAction: RetryFailureAction.SKIP_AND_NOTIFY, teamNotificationFrequency: TeamNotificationFrequency.IMMEDIATELY };
  const db: any = {
    subscription: { findMany: async () => [], update: async ({ data }: any) => Object.assign(job.subscription, data), updateMany: async ({ where, data }: any) => { if (where?.status?.notIn?.includes(job.subscription.status)) return { count: 0 }; Object.assign(job.subscription, data); return { count: 1 }; } },
    billingRetrySettings: { findUnique: async () => settings },
    billingRetryJob: {
      findMany: async () => [...jobs.values()].filter(j => (j.status === RetryJobStatus.PENDING || j.status === RetryJobStatus.UNCERTAIN || (j.status === RetryJobStatus.CLAIMED && j.leaseExpiresAt < now)) && j.scheduledAt <= now).map(j => ({ id: j.id })),
      findUniqueOrThrow: async ({ where }: any) => jobs.get(where.id),
      updateMany: async ({ where, data }: any) => { const current = jobs.get(where.id); if (!current || ![RetryJobStatus.PENDING, RetryJobStatus.UNCERTAIN, RetryJobStatus.CLAIMED].includes(current.status)) return { count: 0 }; if (current.status === RetryJobStatus.CLAIMED && !(current.leaseExpiresAt < now)) return { count: 0 }; Object.assign(current, data); return { count: 1 }; },
      update: async ({ where, data }: any) => { const current = jobs.get(where.id); Object.assign(current, data); return current; },
      create: async ({ data }: any) => { const key = [...jobs.values()].find(j => j.cycleId === data.cycleId && j.kind === data.kind && j.attemptNumber === data.attemptNumber); if (key) throw new Error("duplicate job"); const value = { id: `job-${jobs.size + 1}`, status: RetryJobStatus.PENDING, reconciliationCount: 0, maxReconciliations: 3, ...data }; jobs.set(value.id, value); return value; },
      upsert: async ({ where, create }: any) => { const found = [...jobs.values()].find(j => j.cycleId === where.cycleId_kind_attemptNumber.cycleId && j.kind === where.cycleId_kind_attemptNumber.kind && j.attemptNumber === where.cycleId_kind_attemptNumber.attemptNumber); if (found) return found; const value = { id: `job-${jobs.size + 1}`, status: RetryJobStatus.PENDING, ...create }; jobs.set(value.id, value); return value; },
    },
    billingRetryCycle: {
      findMany: async () => [...cycles.values()].filter(c => c.finalAction && (c.finalActionStatus === "pending" || (c.finalActionStatus === "processing" && c.finalActionLeaseExpiresAt < now))).map(c => ({ ...c, subscription: job.subscription })),
      updateMany: async ({ where, data }: any) => { const cycle = cycles.get(where.id); if (!cycle) return { count: 0 }; if (where.finalActionStatus === "none" && cycle.finalActionStatus !== "none") return { count: 0 }; if (where.OR && !["pending", "processing"].includes(cycle.finalActionStatus)) return { count: 0 }; if (where.status?.not === "succeeded" && cycle.status === "succeeded") return { count: 0 }; Object.assign(cycle, data); return { count: 1 }; },
      update: async ({ where, data }: any) => { const cycle = cycles.get(where.id); Object.assign(cycle, data); return cycle; },
      upsert: async () => job.cycle,
    },
    subscriptionBillingAttempt: { upsert: async ({ where, create, update }: any) => { const key = where.shopId_idempotencyKey.idempotencyKey; const value = attempts.has(key) ? Object.assign(attempts.get(key), update) : { ...create }; attempts.set(key, value); return value; } },
    subscriptionOrder: { upsert: async ({ where, create, update }: any) => { const key = where.shopifyOrderKey; const value = orders.has(key) ? Object.assign(orders.get(key), update) : { ...create }; orders.set(key, value); return value; } },
    notificationOutbox: { upsert: async ({ where, create }: any) => { if (!outbox.has(where.idempotencyKey)) outbox.set(where.idempotencyKey, create); return outbox.get(where.idempotencyKey); } },
    subscriptionStatusHistory: { upsert: async () => ({}) },
    $transaction: async (callback: any) => { transactionCount++; return callback(db); },
  };
  const lifecycle = { calls: [] as string[], execute: async (_id: string, action: string) => { lifecycle.calls.push(action); return { success: true }; } };
  const fetchFn = async (_url: any, init: any) => { externalCalls++; const body = JSON.parse(init.body); const response = overrides.responses?.shift?.() ?? (body.operation === "inventory" ? { success: true, available: true, uncertain: false, errorCode: null, errorMessage: null, billingAttemptId: null, orderId: null, amount: null, currencyCode: null } : { success: true, status: "succeeded", uncertain: false, billingAttemptId: "gid://shopify/SubscriptionBillingAttempt/1", orderId: "gid://shopify/Order/1", amount: "10.00", currencyCode: "BRL", errorCode: null, errorMessage: null }); return Response.json(response); };
  return { job, jobs, cycles, attempts, orders, outbox, settings, db, lifecycle, fetchFn, get transactionCount() { return transactionCount; }, get externalCalls() { return externalCalls; } };
}

test("Promise.all claims one job and creates no duplicate payment job", async () => { const f = fixture(); const a = new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any), b = new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any); await Promise.all([a.run(10, now), b.run(10, now)]); assert.equal(f.externalCalls, 1); assert.equal([...f.jobs.values()].filter(j => j.kind === RetryKind.PAYMENT).length, 1); });
test("expired lease is reclaimed", async () => { const f = fixture({ status: RetryJobStatus.CLAIMED, leaseExpiresAt: new Date(now.getTime() - 1) }); await new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any).run(10, now); assert.equal(f.externalCalls, 1); assert.equal(f.job.status, RetryJobStatus.SUCCEEDED); });
test("failure and next job are persisted in one transaction with independent counter", async () => { const f = fixture({ responses: [{ success: true, available: false, errorCode: "inventory_unavailable", errorMessage: "no stock" }] }); await new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any).processClaimedJob(f.job.id, now, metrics()); assert.equal(f.transactionCount, 1); assert.equal(f.job.status, RetryJobStatus.FAILED); const next = [...f.jobs.values()].find(j => j.id !== f.job.id)!; assert.equal(next.kind, RetryKind.INVENTORY); assert.equal(next.attemptNumber, 1); assert.equal(f.settings.paymentRetryAttempts, 2); });
test("payment success idempotently upserts attempt and real order", async () => { const f = fixture({ kind: RetryKind.PAYMENT, idempotencyKey: "aps:cycle-1:payment:0" }); const engine = new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any); await engine.processClaimedJob(f.job.id, now, metrics()); await engine.processClaimedJob(f.job.id, now, metrics()); assert.equal(f.attempts.size, 1); assert.equal(f.orders.size, 1); assert.equal([...f.orders.values()][0].shopifyOrderId, "gid://shopify/Order/1"); });
test("UNCERTAIN is reconciled with the stored attempt id", async () => { const f = fixture({ kind: RetryKind.PAYMENT, idempotencyKey: "aps:cycle-1:payment:0", responses: [{ success: true, status: "pending", uncertain: true, billingAttemptId: "gid://shopify/SubscriptionBillingAttempt/1" }, { success: true, status: "succeeded", uncertain: false, billingAttemptId: "gid://shopify/SubscriptionBillingAttempt/1", orderId: "gid://shopify/Order/1", amount: "10.00", currencyCode: "BRL" }] }); const engine = new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any); await engine.processClaimedJob(f.job.id, now, metrics()); assert.equal(f.job.status, RetryJobStatus.UNCERTAIN); await engine.processClaimedJob(f.job.id, new Date(now.getTime() + 300_000), metrics()); assert.equal(f.job.status, RetryJobStatus.SUCCEEDED); assert.equal(f.job.reconciliationCount, 1); });
test("zero retries schedules recoverable skip and NEVER creates no outbox", async () => { const f = fixture({ maxRetries: 0, responses: [{ success: true, available: false, errorCode: "inventory_unavailable" }] }); f.settings.inventoryFailureAction = RetryFailureAction.SKIP_AND_NOTIFY; f.settings.teamNotificationFrequency = TeamNotificationFrequency.NEVER; await new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any).run(10, now); assert.equal(f.job.status, RetryJobStatus.EXHAUSTED); assert.equal(f.job.cycle.finalActionStatus, "succeeded"); assert.equal(f.outbox.size, 0); assert.equal(f.job.cycle.nextBillingAdvanced, true); });
for (const [action, expected] of [[RetryFailureAction.PAUSE_AND_NOTIFY, "pause"], [RetryFailureAction.CANCEL_AND_NOTIFY, "cancel"]] as const) test(`${expected} is recovered idempotently after exhaustion`, async () => { const f = fixture({ maxRetries: 0, responses: [{ success: true, available: false }] }); f.settings.inventoryFailureAction = action; await new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any).run(10, now); assert.deepEqual(f.lifecycle.calls, [expected]); assert.equal(f.outbox.size, 1); assert.equal(f.job.cycle.finalActionStatus, "succeeded"); });
test("failed local finalization remains leased and is recovered without duplicate notification", async () => { const f = fixture({ maxRetries: 0, responses: [{ success: true, available: false }] }); let fail = true; const original = f.db.$transaction; f.db.$transaction = async (callback: any) => { if (f.job.cycle.finalActionStatus === "processing" && fail) { fail = false; throw new Error("local failure"); } return original(callback); }; const engine = new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any); await engine.run(10, now); assert.equal(f.job.cycle.finalActionStatus, "processing"); f.job.cycle.finalActionLeaseExpiresAt = new Date(now.getTime() - 1); await engine.run(10, now); assert.equal(f.job.cycle.finalActionStatus, "succeeded"); assert.equal(f.outbox.size, 1); });
test("finite UNCERTAIN reconciliation exhausts into the configured action", async () => { const f = fixture({ kind: RetryKind.PAYMENT, maxReconciliations: 1, idempotencyKey: "aps:cycle-1:payment:0", responses: [{ success: false, uncertain: true, errorCode: "timeout" }] }); await new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any).run(10, now); assert.equal(f.job.status, RetryJobStatus.EXHAUSTED); assert.equal(f.job.errorCode, "reconciliation_exhausted"); assert.equal(f.job.cycle.finalActionStatus, "succeeded"); assert.deepEqual(f.lifecycle.calls, ["pause"]); });
for (const [frequency, expected] of [[TeamNotificationFrequency.IMMEDIATELY, "2026-08-20T12:00:00.000Z"], [TeamNotificationFrequency.DAILY_SUMMARY, "2026-08-21T00:00:00.000Z"], [TeamNotificationFrequency.WEEKLY_SUMMARY, "2026-08-24T00:00:00.000Z"]] as const) test(`${frequency} controls outbox availability`, async () => { const f = fixture({ maxRetries: 0, responses: [{ success: true, available: false }] }); f.settings.teamNotificationFrequency = frequency; await new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any).run(10, now); assert.equal(([...f.outbox.values()][0].availableAt as Date).toISOString(), expected); });
test("rerunning cron does not duplicate charge, attempt, order, job, or notification", async () => { const f = fixture({ kind: RetryKind.PAYMENT, idempotencyKey: "aps:cycle-1:payment:0" }); const engine = new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any); await engine.run(10, now); await engine.run(10, now); assert.equal(f.externalCalls, 1); assert.equal(f.attempts.size, 1); assert.equal(f.orders.size, 1); assert.equal(f.jobs.size, 1); assert.equal(f.outbox.size, 0); });
test("recovered final action never revives or rewrites terminal subscription", async () => { const f = fixture({ maxRetries: 0, responses: [{ success: true, available: false }] }); f.settings.inventoryFailureAction = RetryFailureAction.PAUSE_AND_NOTIFY; f.job.subscription.status = "cancelled"; f.job.cycle.finalAction = RetryFailureAction.PAUSE_AND_NOTIFY; f.job.cycle.finalActionStatus = "pending"; await new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any).run(10, now); assert.equal(f.job.subscription.status, "cancelled"); assert.equal(f.lifecycle.calls.length, 0); });
test("general worker exception records finite UNCERTAIN metadata", async () => { const f = fixture({ kind: RetryKind.PAYMENT, idempotencyKey: "aps:cycle-1:payment:0", responses: [{ success: true, status: "succeeded", billingAttemptId: null, orderId: null }] }); await new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any).run(10, now); assert.equal(f.job.status, RetryJobStatus.UNCERTAIN); assert.equal(f.job.reconciliationCount, 1); assert.equal(f.job.firstUncertainAt.toISOString(), now.toISOString()); assert.equal(f.job.lastReconciledAt.toISOString(), now.toISOString()); assert.equal(f.job.reconciliationDeadlineAt.toISOString(), "2026-08-20T13:00:00.000Z"); });
test("INVENTORY generic uncertainty uses inventoryFailureAction", async () => { const f = fixture({ maxReconciliations: 1 }); f.settings.inventoryFailureAction = RetryFailureAction.CANCEL_AND_NOTIFY; f.settings.paymentFailureAction = RetryFailureAction.PAUSE_AND_NOTIFY; f.job.cycle.billingCycleAt = new Date("invalid"); await new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any).run(10, now); assert.equal(f.job.finalAction, RetryFailureAction.CANCEL_AND_NOTIFY); assert.deepEqual(f.lifecycle.calls, ["cancel"]); });
test("PAYMENT generic uncertainty uses paymentFailureAction", async () => { const f = fixture({ kind: RetryKind.PAYMENT, maxReconciliations: 1, idempotencyKey: "aps:cycle-1:payment:0", responses: [{ success: true, status: "succeeded", billingAttemptId: null, orderId: null }] }); f.settings.inventoryFailureAction = RetryFailureAction.CANCEL_AND_NOTIFY; f.settings.paymentFailureAction = RetryFailureAction.PAUSE_AND_NOTIFY; await new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any).run(10, now); assert.equal(f.job.finalAction, RetryFailureAction.PAUSE_AND_NOTIFY); assert.deepEqual(f.lifecycle.calls, ["pause"]); });
test("transaction rollback keeps current job unchanged when next job creation fails", async () => { const f = fixture({ status: RetryJobStatus.CLAIMED, responses: [{ success: true, available: false, errorCode: "inventory_unavailable" }] }); const originalCreate = f.db.billingRetryJob.create; f.db.billingRetryJob.create = async () => { throw new Error("insert failed"); }; f.db.$transaction = async (callback: any) => { const snapshot = structuredClone(f.job); const ids = new Set(f.jobs.keys()); try { return await callback(f.db); } catch (error) { Object.assign(f.job, snapshot); for (const id of f.jobs.keys()) if (!ids.has(id)) f.jobs.delete(id); throw error; } }; await assert.rejects(new RetryEngineService(f.db, f.fetchFn as any, f.lifecycle as any).processClaimedJob(f.job.id, now, metrics()), /insert failed/); assert.equal(f.job.status, RetryJobStatus.CLAIMED); assert.equal(f.jobs.size, 1); f.db.billingRetryJob.create = originalCreate; });
