import { Resend } from "resend";
import { PrismaClient } from "@prisma/client";
import { decryptCredential, domainFromEmail, normalizeEmail } from "./notification-utils";
import { renderNotification } from "./notification-template";
const LEASE_MS = 60_000, TIMEOUT_MS = 8_000;
export class NotificationOutboxService {
  constructor(private db: any = new PrismaClient(), private clientFactory: (key: string) => any = key => new Resend(key), private now = () => new Date()) {}
  async enqueue(input: { shopId: string; cycleId?: string | null; idempotencyKey: string; frequency?: string; eventType: string; payload: Record<string, unknown>; recipientType: "team" | "customer"; recipientEmail?: string | null; availableAt?: Date }) { const template = renderNotification(input.eventType, input.payload); return this.db.notificationOutbox.upsert({ where: { idempotencyKey: input.idempotencyKey }, create: { shopId: input.shopId, cycleId: input.cycleId ?? null, idempotencyKey: input.idempotencyKey, frequency: input.frequency ?? "IMMEDIATELY", eventType: input.eventType, payload: input.payload, recipientType: input.recipientType, recipientEmail: input.recipientEmail ?? null, subject: template.subject, htmlBody: template.html, textBody: template.text, status: input.recipientEmail ? "pending" : "missing_recipient", availableAt: input.availableAt ?? this.now() }, update: {} }); }
  async run(limit = 20) { const now = this.now(), jobs = await this.db.notificationOutbox.findMany({ where: { OR: [{ status: { in: ["pending", "retry"] }, availableAt: { lte: now } }, { status: "processing", leaseExpiresAt: { lt: now } }] }, orderBy: { availableAt: "asc" }, take: Math.min(50, Math.max(1, limit)) }); const result = { claimed: 0, sent: 0, retried: 0, failed: 0 }; for (const job of jobs) { const claim = await this.db.notificationOutbox.updateMany({ where: { id: job.id, OR: [{ status: { in: ["pending", "retry"] }, availableAt: { lte: now } }, { status: "processing", leaseExpiresAt: { lt: now } }] }, data: { status: "processing", claimedAt: now, leaseExpiresAt: new Date(now.getTime() + LEASE_MS), lastAttemptAt: now, attemptCount: { increment: 1 } } }); if (!claim.count) continue; result.claimed++; await this.send(job.id, result); } return result; }
  private async send(id: string, stats: any) { const job = await this.db.notificationOutbox.findUniqueOrThrow({ where: { id }, include: { shop: { include: { notificationSettings: { include: { activeSendingDomain: true } } } } } }); const settings = job.shop.notificationSettings; let recipients: string[]; try { recipients = job.recipientType === "team" ? (settings?.teamFrequency === "NEVER" ? [] : job.recipientEmail ? [normalizeEmail(job.recipientEmail)] : (settings?.teamEmails || []).map(normalizeEmail)) : [normalizeEmail(job.recipientEmail || job.payload?.email)]; } catch { recipients = []; } if (!recipients.length) { await this.finish(id, "missing_recipient", "missing_recipient"); stats.failed++; return; }
    const sender = await this.sender(settings); if (!sender) { await this.finish(id, "sender_not_verified", "sender_not_verified"); stats.failed++; return; }
    const client = this.clientFactory(sender.key), timeout = new Promise<never>((_, reject) => setTimeout(() => reject(Object.assign(new Error("timeout"), { transient: true })), TIMEOUT_MS));
    try { const rendered = renderNotification(job.eventType, job.payload || {}); const response = await Promise.race([client.emails.send({ from: `${settings?.fromName || sender.name} <${sender.email}>`, to: recipients, replyTo: settings?.replyTo || sender.replyTo || undefined, subject: job.subject || rendered.subject, html: job.htmlBody || rendered.html, text: job.textBody || rendered.text }, { idempotencyKey: job.idempotencyKey }), timeout]); if (response.error || !response.data?.id) throw this.providerError(response.error); await this.db.notificationOutbox.update({ where: { id }, data: { status: "sent", providerMessageId: response.data.id, sentAt: this.now(), leaseExpiresAt: null, errorMessage: null } }); stats.sent++; }
    catch (error: any) { const attempts = job.attemptCount + 1, transient = error?.transient || error?.statusCode === 429 || error?.statusCode >= 500; if (transient && attempts < job.maxAttempts) { await this.db.notificationOutbox.update({ where: { id }, data: { status: "retry", availableAt: new Date(this.now().getTime() + Math.min(3600000, 30000 * 2 ** (attempts - 1))), leaseExpiresAt: null, errorMessage: String(error?.message || "transient_error").slice(0, 250) } }); stats.retried++; } else { await this.finish(id, "permanent_failure", String(error?.message || "permanent_error")); stats.failed++; } }
  }
  private async sender(settings: any) { if (settings?.activeSendingDomain?.sendingVerified && settings.fromEmail && domainFromEmail(settings.fromEmail) === settings.activeSendingDomain.domain && settings.activeSendingDomain.encryptedApiKey) return { key: decryptCredential(settings.activeSendingDomain.encryptedApiKey), email: settings.fromEmail, name: settings.fromName, replyTo: settings.replyTo }; const email = process.env.DEFAULT_NOTIFICATION_FROM_EMAIL, adminKey = process.env.RESEND_API_KEY; if (!email || !adminKey) return null; const normalized = normalizeEmail(email), domain = domainFromEmail(normalized), response = await this.clientFactory(adminKey).domains.list(); const verified = response?.data?.data?.some((item: any) => item.name === domain && (item.status === "verified" || item.capabilities?.sending === "enabled")); if (!verified) return null; return { key: adminKey, email: normalized, name: process.env.DEFAULT_NOTIFICATION_FROM_NAME || "APS", replyTo: process.env.DEFAULT_NOTIFICATION_REPLY_TO }; }
  private providerError(error: any) { const value: any = new Error(error?.message || "resend_error"); value.statusCode = error?.statusCode; value.transient = value.statusCode === 429 || value.statusCode >= 500; return value; }
  private finish(id: string, status: string, errorMessage: string) { return this.db.notificationOutbox.update({ where: { id }, data: { status, errorMessage, leaseExpiresAt: null } }); }
}
