import { NotificationSettings, PrismaClient, SendingDomain } from "@prisma/client";
import { Resend } from "resend";
import { decryptCredential, domainFromEmail, normalizeEmail } from "./notification-utils";
import { renderNotification } from "./notification-template";

const LEASE_MS = 60_000, TIMEOUT_MS = 8_000;
type Metrics = { claimed: number; sent: number; retried: number; failed: number; uncertain: number };
type SettingsWithDomain = NotificationSettings & { activeSendingDomain: SendingDomain | null };
type ProviderError = Error & { statusCode?: number; transient?: boolean };

export class NotificationOutboxService {
  constructor(private db: PrismaClient = new PrismaClient(), private clientFactory: (key: string) => Resend = key => new Resend(key), private now = () => new Date()) {}
  async enqueue(input: { shopId: string; cycleId?: string | null; idempotencyKey: string; frequency?: string; eventType: string; payload: Record<string, unknown>; recipientType: "team" | "customer"; recipientEmail?: string | null; availableAt?: Date }) { const template = renderNotification(input.eventType, input.payload); return this.db.notificationOutbox.upsert({ where: { idempotencyKey: input.idempotencyKey }, create: { shopId: input.shopId, cycleId: input.cycleId ?? null, idempotencyKey: input.idempotencyKey, frequency: input.frequency as never ?? "IMMEDIATELY", eventType: input.eventType, payload: input.payload as never, recipientType: input.recipientType, recipientEmail: input.recipientEmail ?? null, subject: template.subject, htmlBody: template.html, textBody: template.text, status: input.recipientEmail ? "pending" : "missing_recipient", availableAt: input.availableAt ?? this.now() }, update: {} }); }
  async run(limit = 20) { const now = this.now(), jobs = await this.db.notificationOutbox.findMany({ where: { OR: [{ status: { in: ["pending", "retry", "delivery_uncertain"] }, availableAt: { lte: now } }, { status: "processing", leaseExpiresAt: { lt: now } }] }, orderBy: { availableAt: "asc" }, take: Math.min(50, Math.max(1, limit)) }), result: Metrics = { claimed: 0, sent: 0, retried: 0, failed: 0, uncertain: 0 }; for (const job of jobs) await this.claimAndSend(job.id, now, result); return result; }
  async runOne(id: string) { const result: Metrics = { claimed: 0, sent: 0, retried: 0, failed: 0, uncertain: 0 }; await this.claimAndSend(id, this.now(), result); return result; }
  private async claimAndSend(id: string, now: Date, result: Metrics) { const claim = await this.db.notificationOutbox.updateMany({ where: { id, OR: [{ status: { in: ["pending", "retry", "delivery_uncertain"] }, availableAt: { lte: now } }, { status: "processing", leaseExpiresAt: { lt: now } }] }, data: { status: "processing", claimedAt: now, leaseExpiresAt: new Date(now.getTime() + LEASE_MS), lastAttemptAt: now, attemptCount: { increment: 1 } } }); if (!claim.count) return; result.claimed++; await this.send(id, result); }
  private async send(id: string, stats: Metrics) {
    const job = await this.db.notificationOutbox.findUniqueOrThrow({ where: { id }, include: { shop: { include: { notificationSettings: { include: { activeSendingDomain: true } } } } } }), settings = job.shop.notificationSettings;
    if (job.deliveryUncertainAt && (job.attemptCount > job.maxAttempts || (job.deliveryDeadlineAt && this.now() >= job.deliveryDeadlineAt))) { await this.finish(id, "delivery_unresolved", "delivery_reconciliation_exhausted"); stats.failed++; return; }
    let recipients: string[]; try { const payload = job.payload as Record<string, unknown>; recipients = job.recipientType === "team" ? (settings?.teamFrequency === "NEVER" ? [] : job.recipientEmail ? [normalizeEmail(job.recipientEmail)] : (settings?.teamEmails || []).map(normalizeEmail)) : [normalizeEmail(job.recipientEmail || payload.email)]; } catch { recipients = []; }
    if (!recipients.length) { await this.finish(id, "missing_recipient", "missing_recipient"); stats.failed++; return; }
    const sender = await this.sender(settings); if (!sender) { await this.finish(id, "sender_not_verified", "sender_not_verified"); stats.failed++; return; }
    const client = this.clientFactory(sender.key); let timer: ReturnType<typeof setTimeout> | undefined, acceptedId: string | null = null;
    try { const timeout = new Promise<never>((_, reject) => { timer = setTimeout(() => reject(Object.assign(new Error("timeout"), { transient: true })), TIMEOUT_MS); }), rendered = renderNotification(job.eventType, job.payload as Record<string, unknown>), response = await Promise.race([client.emails.send({ from: `${settings?.activeFromName || sender.name} <${sender.email}>`, to: recipients, replyTo: settings?.activeReplyTo || sender.replyTo || undefined, subject: job.subject || rendered.subject, html: job.htmlBody || rendered.html, text: job.textBody || rendered.text }, { idempotencyKey: job.idempotencyKey }), timeout]); if (response.error || !response.data?.id) throw this.providerError(response.error); acceptedId = response.data.id; await this.db.notificationOutbox.update({ where: { id }, data: { status: "sent", providerMessageId: acceptedId, externalSucceededAt: this.now(), sentAt: this.now(), leaseExpiresAt: null, errorMessage: null } }); stats.sent++; }
    catch (error: unknown) { const details = error as ProviderError, attempts = job.attemptCount, transient = details.transient || details.statusCode === 429 || (details.statusCode ?? 0) >= 500; if (acceptedId) { try { await this.db.notificationOutbox.update({ where: { id }, data: { status: "delivery_uncertain", providerMessageId: acceptedId, externalSucceededAt: this.now(), deliveryUncertainAt: this.now(), deliveryDeadlineAt: job.deliveryDeadlineAt ?? new Date(this.now().getTime() + 24 * 60 * 60_000), availableAt: new Date(this.now().getTime() + 60_000), leaseExpiresAt: null, errorMessage: "local_persistence_pending" } }); } catch { /* lease recovery uses the same provider idempotency key */ } stats.uncertain++; } else if (transient && attempts < job.maxAttempts) { await this.db.notificationOutbox.update({ where: { id }, data: { status: "retry", availableAt: new Date(this.now().getTime() + Math.min(3_600_000, 30_000 * 2 ** Math.max(0, attempts - 1))), leaseExpiresAt: null, errorMessage: String(details.message || "transient_error").slice(0, 250) } }); stats.retried++; } else { await this.finish(id, "permanent_failure", String(details.message || "permanent_error")); stats.failed++; } }
    finally { if (timer) clearTimeout(timer); }
  }
  private async sender(settings: SettingsWithDomain | null) { if (settings?.activeSendingDomain?.sendingVerified && settings.activeFromEmail && domainFromEmail(settings.activeFromEmail) === settings.activeSendingDomain.domain && settings.activeSendingDomain.encryptedApiKey) return { key: decryptCredential(settings.activeSendingDomain.encryptedApiKey), email: settings.activeFromEmail, name: settings.activeFromName, replyTo: settings.activeReplyTo }; const email = process.env.DEFAULT_NOTIFICATION_FROM_EMAIL, adminKey = process.env.RESEND_API_KEY; if (!email || !adminKey) return null; const normalized = normalizeEmail(email), domain = domainFromEmail(normalized), response = await this.clientFactory(adminKey).domains.list(), verified = response.data?.data?.some(item => item.name === domain && (item.status === "verified" || item.capabilities?.sending === "enabled")); if (!verified) return null; return { key: adminKey, email: normalized, name: process.env.DEFAULT_NOTIFICATION_FROM_NAME || "APS", replyTo: process.env.DEFAULT_NOTIFICATION_REPLY_TO }; }
  private providerError(error: unknown): ProviderError { const details = error as { message?: string; statusCode?: number }, value: ProviderError = Object.assign(new Error(details?.message || "resend_error"), { statusCode: details?.statusCode }); value.transient = value.statusCode === 429 || (value.statusCode ?? 0) >= 500; return value; }
  private finish(id: string, status: string, errorMessage: string) { return this.db.notificationOutbox.update({ where: { id }, data: { status, errorMessage, leaseExpiresAt: null } }); }
}
