import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";

export const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
export function normalizeEmail(value: unknown) { const email = String(value ?? "").trim().toLowerCase(); if (!EMAIL_RE.test(email) || email.length > 254) throw new Error("invalid_email"); return email; }
export function normalizeDomain(value: unknown) { const domain = String(value ?? "").trim().toLowerCase().replace(/\.$/, ""); if (!/^(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/.test(domain)) throw new Error("invalid_domain"); return domain; }
export function domainFromEmail(email: string) { return normalizeDomain(email.slice(email.lastIndexOf("@") + 1)); }
function key() { const raw = process.env.NOTIFICATION_CREDENTIALS_ENCRYPTION_KEY || ""; const value = /^[0-9a-f]{64}$/i.test(raw) ? Buffer.from(raw, "hex") : Buffer.from(raw, "base64"); if (value.length !== 32) throw new Error("notification_encryption_key_invalid"); return value; }
export function encryptCredential(value: string) { const iv = randomBytes(12), cipher = createCipheriv("aes-256-gcm", key(), iv), encrypted = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]); return ["v1", iv.toString("base64url"), cipher.getAuthTag().toString("base64url"), encrypted.toString("base64url")].join("."); }
export function decryptCredential(value: string) { const [version, iv, tag, data] = value.split("."); if (version !== "v1" || !iv || !tag || !data) throw new Error("invalid_encrypted_credential"); const decipher = createDecipheriv("aes-256-gcm", key(), Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return Buffer.concat([decipher.update(Buffer.from(data, "base64url")), decipher.final()]).toString("utf8"); }
export function escapeHtml(value: unknown) { return String(value ?? "").replace(/[&<>"']/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!); }
export function securePublicSettings(settings: any) { if (!settings) return null; const { activeSendingDomain, ...safe } = settings; return { ...safe, activeSendingDomain: activeSendingDomain ? { id: activeSendingDomain.id, domain: activeSendingDomain.domain, status: activeSendingDomain.status, sendingVerified: activeSendingDomain.sendingVerified } : null }; }
