import { Prisma, PrismaClient, TeamNotificationFrequency } from "@prisma/client";
import { NotificationOutboxService } from "./NotificationOutboxService";

const TOGGLE_BY_EVENT: Record<string, string> = { payment_failed: "paymentFailedEnabled", retry_scheduled: "retryScheduledEnabled", inventory_insufficient: "inventoryFailedEnabled", inventory_retry_scheduled: "inventoryRetryEnabled", subscription_paused: "pausedEnabled", subscription_cancelled: "cancelledEnabled", renewal_succeeded: "renewalSucceededEnabled" };
export function summaryWindow(frequency: TeamNotificationFrequency, now: Date) { const local = new Date(now.getTime() - 3 * 60 * 60_000), start = new Date(Date.UTC(local.getUTCFullYear(), local.getUTCMonth(), local.getUTCDate(), 3)); if (frequency === TeamNotificationFrequency.WEEKLY_SUMMARY) start.setUTCDate(start.getUTCDate() - ((local.getUTCDay() + 6) % 7)); const end = new Date(start); end.setUTCDate(end.getUTCDate() + (frequency === TeamNotificationFrequency.WEEKLY_SUMMARY ? 7 : 1)); return { key: `${frequency}:${start.toISOString()}`, end }; }

export class NotificationEventService {
  constructor(private db: PrismaClient = new PrismaClient(), private outbox = new NotificationOutboxService(db)) {}
  async emit(input: { shopId: string; eventType: string; sourceKey: string; payload: Record<string, unknown>; customerEmail?: string | null; occurredAt?: Date }) {
    if (!("notificationSettings" in this.db)) return { customer: 0, team: 0 };
    const settings = await this.db.notificationSettings.findUnique({ where: { shopId: input.shopId } }); if (!settings) return { customer: 0, team: 0 };
    const enabled = Boolean((settings as unknown as Record<string, unknown>)[TOGGLE_BY_EVENT[input.eventType]]); if (!enabled) return { customer: 0, team: 0 };
    let customer = 0, team = 0;
    if (settings.customerNotificationsEnabled && input.customerEmail) { await this.outbox.enqueue({ shopId: input.shopId, idempotencyKey: `customer:${input.eventType}:${input.sourceKey}`, eventType: input.eventType, payload: input.payload, recipientType: "customer", recipientEmail: input.customerEmail }); customer = 1; }
    if (settings.teamFrequency === TeamNotificationFrequency.NEVER) return { customer, team };
    if (settings.teamFrequency === TeamNotificationFrequency.IMMEDIATELY) { for (const email of settings.teamEmails) { await this.outbox.enqueue({ shopId: input.shopId, idempotencyKey: `team:${input.eventType}:${input.sourceKey}:${email}`, eventType: input.eventType, payload: input.payload, recipientType: "team", recipientEmail: email }); team++; } return { customer, team }; }
    const window = summaryWindow(settings.teamFrequency, input.occurredAt ?? new Date()); await this.db.notificationEvent.upsert({ where: { idempotencyKey: `event:${input.eventType}:${input.sourceKey}` }, create: { shopId: input.shopId, idempotencyKey: `event:${input.eventType}:${input.sourceKey}`, eventType: input.eventType, payload: input.payload as Prisma.InputJsonValue, frequency: settings.teamFrequency, windowKey: window.key, windowEndAt: window.end }, update: {} }); return { customer, team: 1 };
  }
  async materializeSummaries(limit = 20, now = new Date()) { const groups = await this.db.notificationEvent.findMany({ where: { includedInOutboxId: null, windowEndAt: { lte: now }, frequency: { in: [TeamNotificationFrequency.DAILY_SUMMARY, TeamNotificationFrequency.WEEKLY_SUMMARY] } }, distinct: ["shopId", "frequency", "windowKey"], take: limit, select: { shopId: true, frequency: true, windowKey: true } }); let created = 0; for (const group of groups) await this.db.$transaction(async tx => { const events = await tx.notificationEvent.findMany({ where: { shopId: group.shopId, frequency: group.frequency, windowKey: group.windowKey, includedInOutboxId: null }, orderBy: { createdAt: "asc" } }); if (!events.length) return; const settings = await tx.notificationSettings.findUnique({ where: { shopId: group.shopId } }); if (!settings || settings.teamFrequency === TeamNotificationFrequency.NEVER || !settings.teamEmails.length) return; let markerId: string | null = null; for (const email of settings.teamEmails) { const key = `summary:${group.shopId}:${group.frequency}:${group.windowKey}:${email}`; const delivery = await tx.notificationOutbox.upsert({ where: { idempotencyKey: key }, create: { shopId: group.shopId, idempotencyKey: key, frequency: group.frequency, eventType: "team_summary", payload: { frequency: group.frequency, events: events.map(event => ({ type: event.eventType, payload: event.payload })) }, recipientType: "team", recipientEmail: email, includedEventIds: events.map(event => event.id), status: "pending", availableAt: now }, update: {} }); markerId ??= delivery.id; created++; } if (markerId) await tx.notificationEvent.updateMany({ where: { id: { in: events.map(event => event.id) }, includedInOutboxId: null }, data: { includedInOutboxId: markerId } }); }); return { groups: groups.length, created }; }
}
