import { Prisma, PrismaClient, SendingDomain, SendingDomainDnsRecord } from "@prisma/client";
import { Resend } from "resend";
import { domainFromEmail, encryptCredential, normalizeDomain } from "./notification-utils";
import { randomUUID } from "node:crypto";

type DomainWithRecords = SendingDomain & { records: SendingDomainDnsRecord[] };
export type PublicSendingDomain = Pick<SendingDomain, "id" | "domain" | "status" | "sendingVerified" | "lastCheckedAt"> & { records: Array<Pick<SendingDomainDnsRecord, "purpose" | "type" | "name" | "value" | "priority" | "ttl" | "status">> };
type ProviderRecord = { record?: unknown; type?: unknown; name?: unknown; value?: unknown; priority?: number | null; ttl?: unknown; status?: unknown };
type ProviderDomain = { status?: string; capabilities?: { sending?: string }; records?: ProviderRecord[] };
const publicDomain = (domain: DomainWithRecords): PublicSendingDomain => ({ id: domain.id, domain: domain.domain, status: domain.status, sendingVerified: domain.sendingVerified, lastCheckedAt: domain.lastCheckedAt, records: domain.records.map(({ purpose, type, name, value, priority, ttl, status }) => ({ purpose, type, name, value, priority, ttl, status })) });

export class ResendDomainService {
  constructor(private db: PrismaClient = new PrismaClient(), private admin: Resend = new Resend(process.env.RESEND_API_KEY)) {}
  private async context(shopDomain: string) { const shop = await this.db.shop.findUnique({ where: { domain: shopDomain.toLowerCase() } }); if (!shop) throw Object.assign(new Error("shop_not_found"), { statusCode: 404 }); const settings = await this.db.notificationSettings.findUnique({ where: { shopId: shop.id } }); if (!settings?.fromEmail) throw new Error("sender_not_configured"); return { shop, settings, domain: domainFromEmail(settings.fromEmail) }; }
  async get(shopDomain: string): Promise<PublicSendingDomain[]> { const { shop } = await this.context(shopDomain); const values = await this.db.sendingDomain.findMany({ where: { shopId: shop.id, disabledAt: null }, include: { records: { orderBy: { position: "asc" } } }, orderBy: { createdAt: "desc" } }); return values.map(publicDomain); }
  async setup(shopDomain: string): Promise<PublicSendingDomain> {
    const { shop, domain } = await this.context(shopDomain), normalized = normalizeDomain(domain);
    let owned = await this.db.sendingDomain.findUnique({ where: { domain: normalized }, include: { records: { orderBy: { position: "asc" } } } });
    if (owned && owned.shopId !== shop.id) throw Object.assign(new Error("domain_owned_by_another_shop"), { statusCode: 409 });
    if (owned?.providerDomainId && owned.encryptedApiKey) return publicDomain(owned);
    if (!owned?.providerDomainId) { let provider: { id: string; status: string; records?: ProviderRecord[] } | null = null; const domainsApi = this.admin.domains as unknown as { list?: () => Promise<{ data?: { data?: Array<{ id: string; name: string; status: string }> } }> }; if (typeof domainsApi.list === "function") { const listed = await domainsApi.list(), match = listed.data?.data?.find(item => normalizeDomain(item.name) === normalized); if (match) { const recovered = await this.admin.domains.get(match.id); if (!recovered.error && recovered.data) provider = { id: match.id, status: recovered.data.status, records: recovered.data.records }; } } if (!provider) { const created = await this.admin.domains.create({ name: normalized, capabilities: { sending: "enabled", receiving: "disabled" } }); if (created.error || !created.data?.id) throw new Error("resend_domain_create_failed"); provider = { id: created.data.id, status: created.data.status, records: created.data.records }; } const recoveredProvider = provider; owned = await this.db.$transaction(async tx => { const saved = await tx.sendingDomain.upsert({ where: { domain: normalized }, create: { shopId: shop.id, domain: normalized, providerDomainId: recoveredProvider.id, status: recoveredProvider.status }, update: { providerDomainId: recoveredProvider.id, status: recoveredProvider.status, disabledAt: null } }); await this.replaceRecords(tx, saved.id, recoveredProvider.records ?? []); return tx.sendingDomain.findUniqueOrThrow({ where: { id: saved.id }, include: { records: { orderBy: { position: "asc" } } } }); }); }
    if (!owned.providerDomainId) throw new Error("resend_domain_missing_provider_id");
    const apiKey = await this.admin.apiKeys.create({ name: `shop-${shop.id.slice(-12)}-${Date.now()}`.slice(0, 50), permission: "sending_access", domain_id: owned.providerDomainId });
    if (apiKey.error || !apiKey.data?.token || !apiKey.data.id) throw new Error("resend_api_key_create_failed");
    try {
      const pending = await this.db.sendingDomain.update({ where: { id: owned.id }, data: { pendingEncryptedApiKey: encryptCredential(apiKey.data.token), pendingApiKeyId: apiKey.data.id, credentialStatus: "pending_activation" } });
      const activated = await this.db.sendingDomain.update({ where: { id: pending.id }, data: { encryptedApiKey: pending.pendingEncryptedApiKey, apiKeyId: pending.pendingApiKeyId, pendingEncryptedApiKey: null, pendingApiKeyId: null, previousApiKeyId: pending.apiKeyId, credentialStatus: pending.apiKeyId ? "revocation_pending" : "active", credentialVersion: { increment: 1 } }, include: { records: { orderBy: { position: "asc" } } } });
      if (activated.previousApiKeyId) await this.enqueueRevocation(activated.id, activated.previousApiKeyId, "rotation");
      return publicDomain(activated);
    } catch (error) { try { await this.enqueueRevocation(owned.id, apiKey.data.id, "activation_failed"); } catch { /* preserve original error */ } throw error; }
  }
  async rotate(shopDomain: string): Promise<PublicSendingDomain> {
    let domain = await this.single(shopDomain); if (!domain.providerDomainId || !domain.apiKeyId || !domain.sendingVerified) throw new Error("domain_credential_not_active");
    const now = new Date(), operationId = domain.credentialOperationId || randomUUID(), expired = !domain.credentialLeaseExpiresAt || domain.credentialLeaseExpiresAt < now;
    if (domain.pendingApiKeyId && domain.pendingEncryptedApiKey) return this.activatePending(domain);
    if (domain.credentialStatus === "creating" && expired) await this.revokeOrphanedOperation(domain, operationId);
    const claim = await this.db.sendingDomain.updateMany({ where: { id: domain.id, OR: [{ credentialStatus: { in: ["active", "revocation_pending"] } }, { credentialStatus: "creating", credentialLeaseExpiresAt: { lt: now } }] }, data: { credentialStatus: "creating", credentialOperationId: operationId, credentialClaimedAt: now, credentialLeaseExpiresAt: new Date(now.getTime() + 60_000), credentialAttemptCount: { increment: 1 }, credentialError: null } });
    if (!claim.count) throw Object.assign(new Error("credential_rotation_in_progress"), { statusCode: 409 });
    domain = await this.db.sendingDomain.findUniqueOrThrow({ where: { id: domain.id } });
    const name = `rotate-${domain.shopId.slice(-12)}-${operationId}`.slice(0, 50), apiKey = await this.admin.apiKeys.create({ name, permission: "sending_access", domain_id: domain.providerDomainId! });
    if (apiKey.error || !apiKey.data?.token || !apiKey.data.id) { await this.db.sendingDomain.update({ where: { id: domain.id }, data: { credentialStatus: "active", credentialLeaseExpiresAt: null, credentialError: "resend_api_key_create_failed" } }); throw new Error("resend_api_key_create_failed"); }
    try { domain = await this.db.sendingDomain.update({ where: { id: domain.id }, data: { pendingEncryptedApiKey: encryptCredential(apiKey.data.token), pendingApiKeyId: apiKey.data.id, credentialStatus: "pending_activation" } }); return await this.activatePending(domain); }
    catch (error) { try { await this.enqueueRevocation(domain.id, apiKey.data.id, "activation_failed"); } catch { /* durable cleanup will be recovered by operation name */ } await this.db.sendingDomain.updateMany({ where: { id: domain.id }, data: { credentialLeaseExpiresAt: new Date(0), credentialError: error instanceof Error ? error.message.slice(0, 250) : "rotation_failed" } }); throw error; }
  }
  private async activatePending(domain: SendingDomain) { if (!domain.pendingApiKeyId || !domain.pendingEncryptedApiKey || !domain.apiKeyId) throw new Error("pending_credential_incomplete"); const oldId = domain.apiKeyId, activated = await this.db.$transaction(async tx => { const value = await tx.sendingDomain.update({ where: { id: domain.id }, data: { encryptedApiKey: domain.pendingEncryptedApiKey, apiKeyId: domain.pendingApiKeyId, pendingEncryptedApiKey: null, pendingApiKeyId: null, previousApiKeyId: oldId, credentialStatus: "revocation_pending", credentialVersion: { increment: 1 }, credentialLeaseExpiresAt: null, credentialError: null }, include: { records: { orderBy: { position: "asc" } } } }); await tx.sendingCredentialCleanupJob.upsert({ where: { sendingDomainId_providerApiKeyId_reason: { sendingDomainId: domain.id, providerApiKeyId: oldId, reason: "rotation" } }, create: { sendingDomainId: domain.id, providerApiKeyId: oldId, reason: "rotation" }, update: { status: "pending", availableAt: new Date(), completedAt: null } }); return value; }); return publicDomain(activated); }
  private async revokeOrphanedOperation(domain: SendingDomain, operationId: string) { const api = this.admin.apiKeys as unknown as { list?: () => Promise<{ data?: { data?: Array<{ id: string; name?: string }> } }> }; if (!api.list) return; const listed = await api.list(), name = `rotate-${domain.shopId.slice(-12)}-${operationId}`.slice(0, 50); for (const key of listed.data?.data || []) if (key.name === name) await this.enqueueRevocation(domain.id, key.id, "orphaned_rotation"); }
  async verify(shopDomain: string) { const domain = await this.single(shopDomain); const result = await this.admin.domains.verify(domain.providerDomainId!); if (result.error) throw new Error("resend_domain_verify_failed"); return this.refresh(shopDomain); }
  async refresh(shopDomain: string) { const domain = await this.single(shopDomain); const result = await this.admin.domains.get(domain.providerDomainId!); if (result.error || !result.data) throw new Error("resend_domain_refresh_failed"); return this.persistProviderState(domain, result.data); }
  private async single(shopDomain: string) { const { shop, domain } = await this.context(shopDomain); const value = await this.db.sendingDomain.findFirst({ where: { shopId: shop.id, domain, disabledAt: null } }); if (!value?.providerDomainId) throw Object.assign(new Error("domain_not_configured"), { statusCode: 404 }); return value; }
  async persistProviderState(domain: SendingDomain, data: ProviderDomain): Promise<PublicSendingDomain> { return this.db.$transaction(async tx => { const providerVerified = data.status === "verified" || (data.capabilities?.sending === "enabled" && data.status === "partially_verified"), sendingVerified = domain.sendingVerified || providerVerified; await tx.sendingDomain.update({ where: { id: domain.id }, data: { status: sendingVerified && !providerVerified ? domain.status : String(data.status ?? domain.status), sendingVerified, lastCheckedAt: new Date() } }); await this.replaceRecords(tx, domain.id, data.records ?? []); if (providerVerified) { const settings = await tx.notificationSettings.findUnique({ where: { shopId: domain.shopId } }); if (settings?.fromEmail && domainFromEmail(settings.fromEmail) === domain.domain) await tx.notificationSettings.update({ where: { shopId: domain.shopId }, data: { activeSendingDomainId: domain.id, activeFromName: settings.fromName, activeFromEmail: settings.fromEmail, activeReplyTo: settings.replyTo } }); } return publicDomain(await tx.sendingDomain.findUniqueOrThrow({ where: { id: domain.id }, include: { records: { orderBy: { position: "asc" } } } })); }); }
  async runCredentialCleanup(limit = 10, now = new Date()) { const candidates = await this.db.sendingCredentialCleanupJob.findMany({ where: { OR: [{ status: "pending", availableAt: { lte: now } }, { status: "processing", leaseExpiresAt: { lt: now } }] }, take: limit }), metrics = { claimed: 0, revoked: 0, retried: 0, failed: 0 }; for (const job of candidates) { const claim = await this.db.sendingCredentialCleanupJob.updateMany({ where: { id: job.id, OR: [{ status: "pending", availableAt: { lte: now } }, { status: "processing", leaseExpiresAt: { lt: now } }] }, data: { status: "processing", claimedAt: now, leaseExpiresAt: new Date(now.getTime() + 60_000), attemptCount: { increment: 1 } } }); if (!claim.count) continue; metrics.claimed++; try { const result = await this.admin.apiKeys.remove(job.providerApiKeyId); if (result.error && !/not found|already removed/i.test(String(result.error.message || result.error))) throw new Error("resend_api_key_revoke_failed"); await this.db.$transaction(async tx => { await tx.sendingCredentialCleanupJob.update({ where: { id: job.id }, data: { status: "succeeded", completedAt: now, leaseExpiresAt: null, lastError: null } }); if (job.reason === "uninstall") { const remaining = await tx.sendingCredentialCleanupJob.count({ where: { sendingDomainId: job.sendingDomainId, reason: "uninstall", id: { not: job.id }, status: { not: "succeeded" } } }); if (!remaining) await tx.sendingDomain.update({ where: { id: job.sendingDomainId }, data: { encryptedApiKey: null, apiKeyId: null, pendingEncryptedApiKey: null, pendingApiKeyId: null, previousApiKeyId: null, credentialStatus: "revoked" } }); } else await tx.sendingDomain.updateMany({ where: { id: job.sendingDomainId, previousApiKeyId: job.providerApiKeyId }, data: { previousApiKeyId: null, credentialStatus: "active" } }); }); metrics.revoked++; } catch (error) { const attempts = job.attemptCount + 1, exhausted = attempts >= job.maxAttempts; await this.db.sendingCredentialCleanupJob.update({ where: { id: job.id }, data: { status: exhausted ? "failed" : "pending", availableAt: new Date(now.getTime() + Math.min(3_600_000, 30_000 * 2 ** Math.max(0, attempts - 1))), leaseExpiresAt: null, lastError: error instanceof Error ? error.message.slice(0, 250) : "credential_cleanup_failed" } }); exhausted ? metrics.failed++ : metrics.retried++; } } return metrics; }
  private enqueueRevocation(sendingDomainId: string, providerApiKeyId: string, reason: string) { return this.db.sendingCredentialCleanupJob.upsert({ where: { sendingDomainId_providerApiKeyId_reason: { sendingDomainId, providerApiKeyId, reason } }, create: { sendingDomainId, providerApiKeyId, reason }, update: { status: "pending", availableAt: new Date(), completedAt: null } }); }
  private async replaceRecords(tx: Prisma.TransactionClient, sendingDomainId: string, records: ProviderRecord[]) { await tx.sendingDomainDnsRecord.deleteMany({ where: { sendingDomainId } }); if (records.length) await tx.sendingDomainDnsRecord.createMany({ data: records.map((record, position) => ({ sendingDomainId, purpose: String(record.record ?? ""), type: String(record.type ?? ""), name: String(record.name ?? ""), value: String(record.value ?? ""), priority: record.priority ?? null, ttl: record.ttl == null ? null : String(record.ttl), status: String(record.status ?? "not_started"), position })) }); }
}
