import { Resend } from "resend";
import { PrismaClient } from "@prisma/client";
import { ResendDomainService } from "./ResendDomainService";
export class ResendWebhookService {
  constructor(private db: any = new PrismaClient(), private resend: any = new Resend(process.env.RESEND_API_KEY), private domains = new ResendDomainService(db, resend)) {}
  async handle(raw: string, headers: { id?: string; timestamp?: string; signature?: string }) { if (!process.env.RESEND_WEBHOOK_SECRET || !headers.id || !headers.timestamp || !headers.signature) throw Object.assign(new Error("invalid_signature"), { statusCode: 400 }); let event: any; try { event = this.resend.webhooks.verify({ payload: raw, headers, webhookSecret: process.env.RESEND_WEBHOOK_SECRET }); } catch { throw Object.assign(new Error("invalid_signature"), { statusCode: 400 }); }
    const providerEventId = String(event.id || headers.id); const existing = await this.db.notificationDeliveryEvent.findUnique({ where: { providerEventId } }); if (existing) return { duplicate: true };
    const type = String(event.type), data = event.data || {}; if (!["email.delivered", "email.bounced", "email.complained", "email.suppressed", "domain.updated"].includes(type)) return { ignored: true };
    if (type === "domain.updated") { const domain = await this.db.sendingDomain.findUnique({ where: { providerDomainId: String(data.id) } }); if (domain) await this.domains.persistProviderState(domain, data); await this.db.notificationDeliveryEvent.create({ data: { shopId: domain?.shopId, providerEventId, providerDomainId: String(data.id), type, payload: event, occurredAt: event.created_at ? new Date(event.created_at) : null } }); return { processed: true }; }
    const messageId = String(data.email_id || data.id || ""), outbox = messageId ? await this.db.notificationOutbox.findUnique({ where: { providerMessageId: messageId } }) : null; const status = ({ "email.delivered": "delivered", "email.bounced": "bounced", "email.complained": "complained", "email.suppressed": "suppressed" } as any)[type]; await this.db.$transaction(async (tx: any) => { await tx.notificationDeliveryEvent.create({ data: { shopId: outbox?.shopId, providerEventId, providerMessageId: messageId || null, type, payload: event, occurredAt: event.created_at ? new Date(event.created_at) : null } }); if (outbox) await tx.notificationOutbox.update({ where: { id: outbox.id }, data: { status, ...(status === "delivered" ? { deliveredAt: new Date() } : {}) } }); }); return { processed: true }; }
}
