import { Resend } from "resend";
import { PrismaClient } from "@prisma/client";
import { domainFromEmail, encryptCredential, normalizeDomain } from "./notification-utils";
export class ResendDomainService {
  constructor(private db: any = new PrismaClient(), private admin: any = new Resend(process.env.RESEND_API_KEY)) {}
  private async context(shopDomain: string) { const shop = await this.db.shop.findUnique({ where: { domain: shopDomain.toLowerCase() } }); if (!shop) throw Object.assign(new Error("shop_not_found"), { statusCode: 404 }); const settings = await this.db.notificationSettings.findUnique({ where: { shopId: shop.id } }); if (!settings?.fromEmail) throw new Error("sender_not_configured"); return { shop, settings, domain: domainFromEmail(settings.fromEmail) }; }
  async get(shopDomain: string) { const { shop } = await this.context(shopDomain); return this.db.sendingDomain.findMany({ where: { shopId: shop.id, disabledAt: null }, include: { records: { orderBy: { position: "asc" } } }, orderBy: { createdAt: "desc" } }); }
  async setup(shopDomain: string) {
    const { shop, domain } = await this.context(shopDomain); const normalized = normalizeDomain(domain);
    let owned = await this.db.sendingDomain.findUnique({ where: { domain: normalized }, include: { records: true } });
    if (owned && owned.shopId !== shop.id) throw Object.assign(new Error("domain_owned_by_another_shop"), { statusCode: 409 });
    if (owned?.providerDomainId && owned.encryptedApiKey) return owned;
    if (!owned?.providerDomainId) { const created = await this.admin.domains.create({ name: normalized, capabilities: { sending: "enabled", receiving: "disabled" } }); if (created.error || !created.data?.id) throw new Error("resend_domain_create_failed"); owned = await this.db.$transaction(async (tx: any) => { const saved = await tx.sendingDomain.upsert({ where: { domain: normalized }, create: { shopId: shop.id, domain: normalized, providerDomainId: created.data.id, status: created.data.status }, update: { providerDomainId: created.data.id, status: created.data.status, disabledAt: null } }); await this.replaceRecords(tx, saved.id, created.data.records ?? []); return saved; }); }
    const apiKey = await this.admin.apiKeys.create({ name: `shop-${shop.id.slice(-12)}-${Date.now()}`.slice(0, 50), permission: "sending_access", domain_id: owned.providerDomainId }); if (apiKey.error || !apiKey.data?.token) throw new Error("resend_api_key_create_failed");
    return this.db.sendingDomain.upsert({ where: { domain: normalized }, create: { shopId: shop.id, domain: normalized, providerDomainId: owned.providerDomainId, status: owned.status, encryptedApiKey: encryptCredential(apiKey.data.token), apiKeyId: apiKey.data.id }, update: { encryptedApiKey: encryptCredential(apiKey.data.token), apiKeyId: apiKey.data.id }, include: { records: { orderBy: { position: "asc" } } } });
  }
  async verify(shopDomain: string) { const domain = await this.single(shopDomain); const result = await this.admin.domains.verify(domain.providerDomainId); if (result.error) throw new Error("resend_domain_verify_failed"); return this.refresh(shopDomain); }
  async refresh(shopDomain: string) { const domain = await this.single(shopDomain); const result = await this.admin.domains.get(domain.providerDomainId); if (result.error || !result.data) throw new Error("resend_domain_refresh_failed"); return this.persistProviderState(domain, result.data); }
  private async single(shopDomain: string) { const { shop, domain } = await this.context(shopDomain); const value = await this.db.sendingDomain.findFirst({ where: { shopId: shop.id, domain, disabledAt: null } }); if (!value?.providerDomainId) throw Object.assign(new Error("domain_not_configured"), { statusCode: 404 }); return value; }
  async persistProviderState(domain: any, data: any) { return this.db.$transaction(async (tx: any) => { const sendingVerified = data.status === "verified" || data.capabilities?.sending === "enabled" && data.status === "partially_verified"; const saved = await tx.sendingDomain.update({ where: { id: domain.id }, data: { status: data.status, sendingVerified, lastCheckedAt: new Date() } }); await this.replaceRecords(tx, domain.id, data.records ?? []); if (sendingVerified) { const settings = await tx.notificationSettings.findUnique({ where: { shopId: domain.shopId } }); if (settings?.fromEmail && domainFromEmail(settings.fromEmail) === domain.domain) await tx.notificationSettings.update({ where: { shopId: domain.shopId }, data: { activeSendingDomainId: domain.id } }); } return tx.sendingDomain.findUnique({ where: { id: saved.id }, include: { records: { orderBy: { position: "asc" } } } }); }); }
  private async replaceRecords(tx: any, sendingDomainId: string, records: any[]) { await tx.sendingDomainDnsRecord.deleteMany({ where: { sendingDomainId } }); if (records.length) await tx.sendingDomainDnsRecord.createMany({ data: records.map((r, position) => ({ sendingDomainId, purpose: String(r.record ?? ""), type: String(r.type ?? ""), name: String(r.name ?? ""), value: String(r.value ?? ""), priority: r.priority ?? null, ttl: r.ttl == null ? null : String(r.ttl), status: String(r.status ?? "not_started"), position })) }); }
}
