import assert from "node:assert/strict";
import test from "node:test";
import { PrismaShopifyEventRepository } from "../shopify-event.repository";

const contractId = "gid://shopify/SubscriptionContract/1";
function contractEvent(status: "PAUSED" | "CANCELLED", webhookId: string): any { return { shop: "one.myshopify.com", topic: "subscription_contracts/update", webhookId, payload: {}, receivedAt: new Date("2026-08-24T12:00:00Z"), contract: { id: contractId, status, currencyCode: "BRL", revisionId: `gid://shopify/SubscriptionContractRevision/${status === "PAUSED" ? 2 : 3}`, billingPolicy: { interval: "MONTH", intervalCount: 1 }, deliveryPolicy: { interval: "MONTH", intervalCount: 1 }, lines: [] } }; }

function webhookFixture(initialStatus = "active") { const subscription: any = { id: "sub-1", shopId: "shop-1", status: initialStatus, lastPaymentStatus: null, shopifyRevisionId: "gid://shopify/SubscriptionContractRevision/1", shopifyCustomerEmail: "customer@example.com", gateway: "shopify" }, emitted: any[] = []; let committed = false; const tx: any = { shop: { update: async () => ({}) }, subscription: { findUnique: async () => ({ ...subscription }), upsert: async ({ update }: any) => { Object.assign(subscription, update); return { id: subscription.id, gateway: subscription.gateway, shopifyCustomerEmail: subscription.shopifyCustomerEmail }; }, update: async ({ data }: any) => Object.assign(subscription, data) }, subscriptionStatusHistory: { upsert: async () => ({}) }, subscriptionLine: { updateMany: async () => ({ count: 0 }), upsert: async () => ({}) }, webhookEvent: { update: async () => { committed = true; return {}; } } }, db: any = { $transaction: async (fn: any) => fn(tx), subscription: { findUnique: tx.subscription.findUnique } }, notifications: any = { emit: async (value: any) => { assert.equal(committed, true); if (!emitted.some(item => item.shopId === value.shopId && item.eventType === value.eventType && item.sourceKey === value.sourceKey)) emitted.push(value); } }, repository = new PrismaShopifyEventRepository(db, notifications); return { subscription, emitted, repository, notifications, markCommitted: () => { committed = true; } }; }

test("ACTIVE to PAUSED webhook emits notification only after local commit", async () => { const f = webhookFixture(); await f.repository.processEvent(contractEvent("PAUSED", "w-pause"), "shop-1"); assert.equal(f.subscription.status, "paused"); assert.equal(f.emitted.length, 1); assert.equal(f.emitted[0].eventType, "subscription_paused"); });
test("ACTIVE to CANCELLED webhook emits notification only after local commit", async () => { const f = webhookFixture(); await f.repository.processEvent(contractEvent("CANCELLED", "w-cancel"), "shop-1"); assert.equal(f.subscription.status, "cancelled"); assert.equal(f.emitted.length, 1); assert.equal(f.emitted[0].eventType, "subscription_cancelled"); });
test("lifecycle notification followed by webhook does not duplicate delivery", async () => { const f = webhookFixture(), sourceKey = `contract:${contractId}:paused`; f.markCommitted(); await f.notifications.emit({ shopId: "shop-1", eventType: "subscription_paused", sourceKey }); await f.repository.processEvent(contractEvent("PAUSED", "w-after-lifecycle"), "shop-1"); assert.equal(f.emitted.length, 1); assert.equal(f.emitted[0].sourceKey, sourceKey); });

test("uninstall durably queues active pending previous and orphaned credential IDs", async () => { const queued = new Set<string>(), tx: any = { shop: { update: async () => ({}) }, sendingDomain: { findMany: async () => [{ id: "d1", apiKeyId: "active", pendingApiKeyId: "pending", previousApiKeyId: "previous", cleanupJobs: [{ providerApiKeyId: "orphan" }] }], updateMany: async () => ({ count: 1 }) }, sendingCredentialCleanupJob: { upsert: async ({ create }: any) => { queued.add(create.providerApiKeyId); return create; } }, webhookEvent: { update: async () => ({}) } }, db: any = { $transaction: async (fn: any) => fn(tx) }; await new PrismaShopifyEventRepository(db, { emit: async () => ({}) } as never).processEvent({ shop: "one.myshopify.com", topic: "app/uninstalled", webhookId: "uninstall", payload: {}, receivedAt: new Date() } as any, "shop-1"); assert.deepEqual([...queued].sort(), ["active", "orphan", "pending", "previous"]); });
