import assert from "node:assert/strict";
import test from "node:test";
import { ResendDomainService } from "../ResendDomainService";
import { decryptCredential } from "../notification-utils";
process.env.NOTIFICATION_CREDENTIALS_ENCRYPTION_KEY = Buffer.alloc(32, 9).toString("base64");

test("credential rotation persists pending, activates, and queues old-key revocation", async () => { const jobs = new Map<string, any>(), domain: any = { id: "d1", shopId: "one", domain: "example.com", providerDomainId: "pd1", status: "verified", sendingVerified: true, encryptedApiKey: "old-cipher", apiKeyId: "old-key", pendingEncryptedApiKey: null, pendingApiKeyId: null, previousApiKeyId: null, credentialStatus: "active", credentialVersion: 1, lastCheckedAt: null, disabledAt: null, createdAt: new Date(), updatedAt: new Date(), records: [] }, settings = { fromEmail: "mail@example.com" }, db: any = { shop: { findUnique: async () => ({ id: "one" }) }, notificationSettings: { findUnique: async () => settings }, sendingDomain: { findFirst: async () => domain, update: async ({ data, include }: any) => { const resolved = { ...data, credentialVersion: typeof data.credentialVersion === "object" ? domain.credentialVersion + 1 : data.credentialVersion }; Object.assign(domain, resolved); return include ? { ...domain, records: [] } : domain; } }, sendingCredentialCleanupJob: { upsert: async ({ where, create }: any) => { const key = JSON.stringify(where); if (!jobs.has(key)) jobs.set(key, create); return jobs.get(key); } } }, provider: any = { apiKeys: { create: async () => ({ data: { id: "new-key", token: "re_new" } }) } }, value = await new ResendDomainService(db, provider).rotate("one.myshopify.com"); assert.equal(value.id, "d1"); assert.equal(domain.apiKeyId, "new-key"); assert.equal(decryptCredential(domain.encryptedApiKey), "re_new"); assert.equal(domain.previousApiKeyId, "old-key"); assert.equal(domain.credentialStatus, "revocation_pending"); assert.equal(jobs.size, 1); });

test("failed revocation remains durable and an expired lease resumes safely", async () => { const now = new Date("2026-08-21T12:00:00Z"), job: any = { id: "c1", sendingDomainId: "d1", providerApiKeyId: "old-key", reason: "rotation", status: "processing", attemptCount: 0, maxAttempts: 3, availableAt: now, leaseExpiresAt: new Date(now.getTime() - 1) }, domain: any = { id: "d1", previousApiKeyId: "old-key", credentialStatus: "revocation_pending" }; let failures = 1, removes = 0; const db: any = { sendingCredentialCleanupJob: { findMany: async () => [job], updateMany: async () => { job.status = "processing"; job.attemptCount++; return { count: 1 }; }, update: async ({ data }: any) => Object.assign(job, data) }, sendingDomain: { updateMany: async ({ data }: any) => Object.assign(domain, data), update: async ({ data }: any) => Object.assign(domain, data) }, $transaction: async (fn: any) => fn(db) }, provider: any = { apiKeys: { remove: async () => { removes++; if (failures--) return { error: { message: "temporary" } }; return { data: {} }; } } }, service = new ResendDomainService(db, provider); const first = await service.runCredentialCleanup(10, now); assert.equal(first.retried, 1); assert.equal(job.status, "pending"); const second = await service.runCredentialCleanup(10, new Date(now.getTime() + 60_000)); assert.equal(second.revoked, 1); assert.equal(domain.previousApiKeyId, null); assert.equal(domain.credentialStatus, "active"); assert.equal(removes, 2); });

test("uninstall cleanup revokes before clearing the local credential", async () => { const now = new Date(), job: any = { id: "u1", sendingDomainId: "d1", providerApiKeyId: "key", reason: "uninstall", status: "pending", attemptCount: 0, maxAttempts: 3, availableAt: now, leaseExpiresAt: null }, domain: any = { encryptedApiKey: "cipher", apiKeyId: "key", credentialStatus: "uninstall_pending" }; let observedCipher: string | null = null; const db: any = { sendingCredentialCleanupJob: { findMany: async () => [job], updateMany: async () => { job.attemptCount++; return { count: 1 }; }, update: async ({ data }: any) => Object.assign(job, data) }, sendingDomain: { update: async ({ data }: any) => Object.assign(domain, data), updateMany: async () => ({ count: 0 }) }, $transaction: async (fn: any) => fn(db) }, provider: any = { apiKeys: { remove: async () => { observedCipher = domain.encryptedApiKey; return { data: {} }; } } }; await new ResendDomainService(db, provider).runCredentialCleanup(10, now); assert.equal(observedCipher, "cipher"); assert.equal(domain.encryptedApiKey, null); assert.equal(domain.credentialStatus, "revoked"); });
