import assert from "node:assert/strict";
import test from "node:test";
import { TeamNotificationFrequency } from "@prisma/client";
import { NotificationEventService } from "../NotificationEventService";
import { renderNotification } from "../notification-template";

test("global and individual toggles suppress customer and team notification production", async () => { let enqueued = 0; const db = { notificationSettings: { findUnique: async () => ({ customerNotificationsEnabled: false, paymentFailedEnabled: false, teamFrequency: TeamNotificationFrequency.IMMEDIATELY, teamEmails: ["team@example.com"] }) } }, outbox = { enqueue: async () => { enqueued++; } }, service = new NotificationEventService(db as never, outbox as never); assert.deepEqual(await service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "attempt", payload: {}, customerEmail: "customer@example.com" }), { customer: 0, team: 0 }); assert.equal(enqueued, 0); });

test("customer recipient is never replaced by a team address", async () => { const recipients: string[] = [], db = { notificationSettings: { findUnique: async () => ({ customerNotificationsEnabled: true, paymentFailedEnabled: true, teamFrequency: TeamNotificationFrequency.IMMEDIATELY, teamEmails: ["team@example.com"] }) } }, outbox = { enqueue: async (input: { recipientEmail?: string | null }) => { recipients.push(String(input.recipientEmail)); } }, service = new NotificationEventService(db as never, outbox as never); await service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "attempt", payload: {}, customerEmail: "customer@example.com" }); assert.deepEqual(recipients, ["customer@example.com", "team@example.com"]); });

test("DAILY summary concurrency creates one delivery per recipient and records all included events", async () => { const now = new Date("2026-08-22T03:01:00Z"), events: any[] = [{ id: "e1", shopId: "one", frequency: TeamNotificationFrequency.DAILY_SUMMARY, windowKey: "DAILY_SUMMARY:2026-08-21T03:00:00.000Z", windowEndAt: new Date("2026-08-22T03:00:00Z"), includedInOutboxId: null, eventType: "payment_failed", payload: {}, createdAt: new Date(1) }, { id: "e2", shopId: "one", frequency: TeamNotificationFrequency.DAILY_SUMMARY, windowKey: "DAILY_SUMMARY:2026-08-21T03:00:00.000Z", windowEndAt: new Date("2026-08-22T03:00:00Z"), includedInOutboxId: null, eventType: "retry_scheduled", payload: {}, createdAt: new Date(2) }], deliveries = new Map<string, any>(); const db: any = { notificationEvent: { findMany: async ({ select }: any) => select ? [{ shopId: "one", frequency: TeamNotificationFrequency.DAILY_SUMMARY, windowKey: events[0].windowKey }] : events.filter(event => !event.includedInOutboxId), updateMany: async ({ data }: any) => { for (const event of events) if (!event.includedInOutboxId) event.includedInOutboxId = data.includedInOutboxId; return { count: events.length }; } }, notificationSettings: { findUnique: async () => ({ teamFrequency: TeamNotificationFrequency.DAILY_SUMMARY, teamEmails: ["a@example.com", "b@example.com"] }) }, notificationOutbox: { findUnique: async ({ where }: any) => deliveries.get(where.idempotencyKey) || null, update: async ({ where, data }: any) => { const delivery = [...deliveries.values()].find(value => value.id === where.id); Object.assign(delivery, data); return delivery; }, upsert: async ({ where, create }: any) => { if (!deliveries.has(where.idempotencyKey)) deliveries.set(where.idempotencyKey, { id: `o${deliveries.size + 1}`, ...create }); return deliveries.get(where.idempotencyKey); } }, $transaction: async (fn: any) => fn(db) }, service = new NotificationEventService(db, {} as never); await Promise.all([service.materializeSummaries(20, now), service.materializeSummaries(20, now)]); assert.equal(deliveries.size, 2); for (const delivery of deliveries.values()) assert.deepEqual(delivery.includedEventIds, ["e1", "e2"]); assert.equal(events.every(event => event.includedInOutboxId), true); });

test("WEEKLY and NEVER do not lose or incorrectly deliver events", async () => { let enqueued = 0, stored = 0; const settings: { customerNotificationsEnabled: boolean; paymentFailedEnabled: boolean; teamFrequency: TeamNotificationFrequency; teamEmails: string[] } = { customerNotificationsEnabled: false, paymentFailedEnabled: true, teamFrequency: TeamNotificationFrequency.NEVER, teamEmails: ["team@example.com"] }, db: any = { notificationSettings: { findUnique: async () => settings }, notificationEvent: { upsert: async () => { stored++; } } }, service = new NotificationEventService(db, { enqueue: async () => { enqueued++; } } as never); await service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "never", payload: {} }); assert.equal(enqueued, 0); assert.equal(stored, 0); settings.teamFrequency = TeamNotificationFrequency.WEEKLY_SUMMARY; await service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "weekly", payload: {} }); assert.equal(stored, 1); });

test("same source and recipient remain isolated between tenants", async () => { const keys: string[] = [], db: any = { notificationSettings: { findUnique: async () => ({ customerNotificationsEnabled: true, paymentFailedEnabled: true, teamFrequency: TeamNotificationFrequency.NEVER, teamEmails: [] }) } }, outbox: any = { enqueue: async (input: { idempotencyKey: string }) => { keys.push(input.idempotencyKey); return { id: `o${keys.length}` }; }, runOne: async () => ({}) }, service = new NotificationEventService(db, outbox, () => undefined); await Promise.all([service.emit({ shopId: "shop-a", eventType: "payment_failed", sourceKey: "attempt-1", payload: {}, customerEmail: "same@example.com" }), service.emit({ shopId: "shop-b", eventType: "payment_failed", sourceKey: "attempt-1", payload: {}, customerEmail: "same@example.com" })]); assert.equal(new Set(keys).size, 2); assert.ok(keys.some(key => key.includes("shop-a"))); assert.ok(keys.some(key => key.includes("shop-b"))); });

for (const frequency of [TeamNotificationFrequency.DAILY_SUMMARY, TeamNotificationFrequency.WEEKLY_SUMMARY]) test(`${frequency} renders HTML and plain text with escaped summary content`, () => { const rendered = renderNotification("team_summary", { frequency, shop: "<script>alert(1)</script>", windowStart: "2026-08-17T03:00:00Z", windowEnd: "2026-08-24T03:00:00Z", events: [{ type: "payment_failed", payload: { customer: "<img src=x onerror=alert(1)>" } }] }); assert.match(rendered.html, /&lt;script&gt;/); assert.doesNotMatch(rendered.html, /<script>/); assert.match(rendered.html, /&lt;img/); assert.match(rendered.text, /Resumo de assinaturas/); assert.match(rendered.text, /Total geral: 1/); });

test("IMMEDIATELY persists outbox before waitUntil and webhook path does not await Resend", async () => { const order: string[] = [], pending = new Promise<void>(() => undefined), db: any = { notificationSettings: { findUnique: async () => ({ customerNotificationsEnabled: true, paymentFailedEnabled: true, teamFrequency: TeamNotificationFrequency.NEVER, teamEmails: [] }) } }, outbox: any = { enqueue: async () => { order.push("enqueue"); return { id: "o1" }; }, runOne: () => { order.push("resend-started"); return pending; } }, service = new NotificationEventService(db, outbox, work => { order.push("waitUntil"); void work; }); await service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "attempt", payload: {}, customerEmail: "customer@example.com" }); assert.deepEqual(order, ["enqueue", "resend-started", "waitUntil"]); });

function historicalEmailFixture(providerEmail: unknown, responseOk = true) { const recipients: string[] = [], updates: any[] = [], db: any = { notificationSettings: { findUnique: async () => ({ customerNotificationsEnabled: true, paymentFailedEnabled: true, teamFrequency: TeamNotificationFrequency.NEVER, teamEmails: [] }) }, subscription: { findFirst: async () => ({ id: "sub-1", shopifyContractId: "gid://shopify/SubscriptionContract/1", shopifyCustomerEmail: null, shop: { domain: "one.myshopify.com", accessToken: "token" } }), updateMany: async (value: any) => { updates.push(value); return { count: 1 }; } } }, outbox: any = { enqueue: async (input: any) => { recipients.push(input.recipientEmail); return {}; }, runOne: async () => ({}) }, fetchFn: any = async () => Response.json({ data: { subscriptionContract: { customer: { defaultEmailAddress: { emailAddress: providerEmail } } } } }, { status: responseOk ? 200 : 500 }), service = new NotificationEventService(db, outbox, () => undefined, fetchFn); return { recipients, updates, service }; }

test("historical subscription resolves a valid customer email through read-only Shopify query", async () => { const f = historicalEmailFixture("Customer@Example.com"); await f.service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "a", payload: { subscriptionId: "sub-1" } }); assert.deepEqual(f.recipients, ["customer@example.com"]); assert.equal(f.updates.length, 1); });
test("historical subscription with nonexistent email creates no customer delivery", async () => { const f = historicalEmailFixture(null); await f.service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "a", payload: { subscriptionId: "sub-1" } }); assert.equal(f.recipients.length, 0); assert.equal(f.updates.length, 0); });
test("historical subscription rejects invalid Shopify customer email", async () => { const f = historicalEmailFixture("not-an-email"); await f.service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "a", payload: { subscriptionId: "sub-1" } }); assert.equal(f.recipients.length, 0); assert.equal(f.updates.length, 0); });
test("historical subscription tolerates Shopify query failure without using team email", async () => { const f = historicalEmailFixture("team@example.com", false); await f.service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "a", payload: { subscriptionId: "sub-1" } }); assert.equal(f.recipients.length, 0); assert.equal(f.updates.length, 0); });
test("team email never substitutes a missing historical customer email", async () => { const f = historicalEmailFixture(null); await f.service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "a", payload: { subscriptionId: "sub-1" } }); assert.equal(f.recipients.includes("team@example.com"), false); });

test("late event joins pending summary, included payload is exact, and sent summary gets deterministic supplement", async () => { const now = new Date("2026-08-24T03:01:00Z"), windowKey = "DAILY_SUMMARY:2026-08-23T03:00:00.000Z", events: any[] = [], deliveries = new Map<string, any>(), db: any = { notificationEvent: { findMany: async ({ select }: any) => select ? (events.some(e => !e.includedInOutboxId) ? [{ shopId: "one", frequency: TeamNotificationFrequency.DAILY_SUMMARY, windowKey }] : []) : events.filter(e => !e.includedInOutboxId), updateMany: async ({ where, data }: any) => { let count = 0; for (const event of events) if (where.id.in.includes(event.id) && !event.includedInOutboxId) { event.includedInOutboxId = data.includedInOutboxId; count++; } return { count }; } }, notificationSettings: { findUnique: async () => ({ teamFrequency: TeamNotificationFrequency.DAILY_SUMMARY, teamEmails: ["team@example.com"], shop: { name: "One" } }) }, notificationOutbox: { findUnique: async ({ where }: any) => deliveries.get(where.idempotencyKey) || null, update: async ({ where, data }: any) => { const row = [...deliveries.values()].find(value => value.id === where.id); Object.assign(row, data); return row; }, upsert: async ({ where, create }: any) => { if (!deliveries.has(where.idempotencyKey)) deliveries.set(where.idempotencyKey, { id: `o${deliveries.size + 1}`, ...create }); return deliveries.get(where.idempotencyKey); } }, $transaction: async (fn: any) => fn(db) }, service = new NotificationEventService(db, {} as never), add = (id: string) => events.push({ id, shopId: "one", frequency: TeamNotificationFrequency.DAILY_SUMMARY, windowKey, windowEndAt: new Date("2026-08-24T03:00:00Z"), includedInOutboxId: null, eventType: "payment_failed", payload: { id }, createdAt: new Date() }); add("e1"); await service.materializeSummaries(20, now); add("e2"); await service.materializeSummaries(20, now); const base = [...deliveries.values()][0]; assert.deepEqual(base.includedEventIds, ["e1", "e2"]); assert.deepEqual(base.payload.events.map((e: any) => e.payload.id), ["e1", "e2"]); base.status = "sent"; add("e3"); await service.materializeSummaries(20, now); assert.equal(deliveries.size, 2); const supplement = [...deliveries.entries()].find(([key]) => key.includes(":supplement:e3")); assert.ok(supplement); assert.deepEqual(supplement![1].includedEventIds, ["e3"]); assert.equal(events.every(event => event.includedInOutboxId), true); });
