import assert from "node:assert/strict";
import test from "node:test";
import { NotificationSettingsService } from "../NotificationSettingsService";
import { ResendDomainService } from "../ResendDomainService";
import { NotificationOutboxService } from "../NotificationOutboxService";
import { decryptCredential, encryptCredential } from "../notification-utils";
import { formatDate, formatMoney, renderNotification } from "../notification-template";
import { ResendWebhookService } from "../ResendWebhookService";
process.env.NOTIFICATION_CREDENTIALS_ENCRYPTION_KEY = Buffer.alloc(32, 7).toString("base64");

test("credential uses authenticated encryption and never stores plaintext", () => { const encrypted = encryptCredential("re_secret"); assert.equal(encrypted.includes("re_secret"), false); assert.equal(decryptCredential(encrypted), "re_secret"); assert.throws(() => decryptCredential(encrypted.slice(0, -1) + "x")); });
test("templates escape content and format pt-BR money and Sao Paulo dates", () => { const rendered = renderNotification("payment_failed", { name: "<script>", amount: 10.5, currency: "BRL", nextAt: "2026-08-21T12:00:00Z" }); assert.equal(rendered.html.includes("<script>"), false); assert.match(formatMoney(10.5), /10,50/); assert.match(formatDate("2026-08-21T12:00:00Z"), /09:00/); });

function settingsDb() { const shops = new Map([["one.myshopify.com", { id: "one", domain: "one.myshopify.com" }], ["two.myshopify.com", { id: "two", domain: "two.myshopify.com" }]]), values = new Map<string, any>(); return { values, shop: { findUnique: async ({ where }: any) => shops.get(where.domain) }, notificationSettings: { findUnique: async ({ where }: any) => values.get(where.shopId) || null, upsert: async ({ where, create, update }: any) => { const value = { ...(values.get(where.shopId) || create), ...update, shopId: where.shopId, activeSendingDomain: values.get(where.shopId)?.activeSendingDomain || null }; values.set(where.shopId, value); return value; } } }; }
test("settings are isolated by shop and normalize recipients", async () => { const db = settingsDb(), service = new NotificationSettingsService(db as any); await service.save("one.myshopify.com", { fromName: "Loja 1", fromEmail: "FROM@EXAMPLE.COM", replyTo: "reply@example.com", teamEmails: ["TEAM@example.com"], teamFrequency: "IMMEDIATELY", customerNotificationsEnabled: true }); assert.equal((await service.get("one.myshopify.com")).fromEmail, "from@example.com"); assert.equal((await service.get("two.myshopify.com")).fromEmail, null); });
test("sender change keeps previous verified domain active", async () => { const db = settingsDb(); db.values.set("one", { shopId: "one", fromEmail: "old@old.test", activeSendingDomainId: "d1", activeSendingDomain: { id: "d1", domain: "old.test", sendingVerified: true } }); await new NotificationSettingsService(db as any).save("one.myshopify.com", { fromName: "Loja", fromEmail: "new@new.test", replyTo: "reply@new.test", teamEmails: ["team@new.test"], teamFrequency: "NEVER" }); assert.equal(db.values.get("one").activeSendingDomainId, "d1"); });

test("domain setup is idempotent, tenant-safe and persists exact DNS records", async () => { let creates = 0; const domains = new Map<string, any>(), records: any[] = []; const db: any = { shop: { findUnique: async () => ({ id: "one" }) }, notificationSettings: { findUnique: async () => ({ fromEmail: "mail@example.com" }) }, sendingDomain: { findUnique: async ({ where }: any) => domains.get(where.domain), upsert: async ({ create }: any) => { const value = { id: "d1", ...create }; domains.set(create.domain, value); return value; }, findFirst: async () => null }, sendingDomainDnsRecord: { deleteMany: async () => {}, createMany: async ({ data }: any) => records.push(...data) }, $transaction: async (fn: any) => fn(db) }; db.sendingDomain.findUnique = async ({ where }: any) => where.id ? { ...domains.get("example.com"), records } : domains.get(where.domain); const provider: any = { domains: { create: async () => { creates++; return { data: { id: "pd1", status: "not_started", records: [{ record: "DKIM", type: "CNAME", name: "key", value: "target", ttl: "Auto", status: "pending" }] } }; } }, apiKeys: { create: async () => ({ data: { id: "key1", token: "re_token" } }) } }; const service = new ResendDomainService(db, provider); const first = await service.setup("one.myshopify.com"); const second = await service.setup("one.myshopify.com"); assert.equal(creates, 1); assert.equal(records[0].type, "CNAME"); assert.equal(records[0].value, "target"); assert.equal(first.providerDomainId, second.providerDomainId); domains.set("stolen.test", { shopId: "two", domain: "stolen.test", providerDomainId: "p2" }); db.notificationSettings.findUnique = async () => ({ fromEmail: "mail@stolen.test" }); await assert.rejects(service.setup("one.myshopify.com"), /domain_owned_by_another_shop/); });

function outboxFixture(response: any = { data: { id: "email-1" } }) { const now = new Date("2026-08-21T12:00:00Z"), jobs = new Map<string, any>(); const db: any = { notificationOutbox: { upsert: async ({ where, create }: any) => { if (!jobs.has(where.idempotencyKey)) jobs.set(where.idempotencyKey, { id: "j1", attemptCount: 0, maxAttempts: 3, ...create }); return jobs.get(where.idempotencyKey); }, findMany: async () => [...jobs.values()].filter(j => ["pending", "retry"].includes(j.status) || j.status === "processing" && j.leaseExpiresAt < now), updateMany: async ({ where, data }: any) => { const job = [...jobs.values()].find(j => j.id === where.id); if (!job || job.status === "processing" && job.leaseExpiresAt >= now) return { count: 0 }; Object.assign(job, data, { attemptCount: job.attemptCount + 1 }); return { count: 1 }; }, findUniqueOrThrow: async ({ where }: any) => ({ ...[...jobs.values()].find(j => j.id === where.id), shop: { notificationSettings: { fromName: "Loja", fromEmail: "mail@example.com", replyTo: "reply@example.com", activeSendingDomain: { domain: "example.com", sendingVerified: true, encryptedApiKey: encryptCredential("re_domain") } } } }), update: async ({ where, data }: any) => { const job = [...jobs.values()].find(j => j.id === where.id); Object.assign(job, data); return job; } } }; let sends = 0; const service = new NotificationOutboxService(db, () => ({ emails: { send: async () => { sends++; return response; } } }), () => now); return { service, jobs, get sends() { return sends; } }; }
test("outbox enqueue and Promise.all claim are idempotent", async () => { const f = outboxFixture(); await Promise.all([f.service.enqueue({ shopId: "one", idempotencyKey: "same", eventType: "payment_failed", payload: {}, recipientType: "team", recipientEmail: "team@example.com" }), f.service.enqueue({ shopId: "one", idempotencyKey: "same", eventType: "payment_failed", payload: {}, recipientType: "team", recipientEmail: "team@example.com" })]); await Promise.all([f.service.run(), f.service.run()]); assert.equal(f.jobs.size, 1); assert.equal(f.sends, 1); assert.equal([...f.jobs.values()][0].status, "sent"); });
test("expired lease is recovered and missing recipient is terminal", async () => { const f = outboxFixture(); const job: any = await f.service.enqueue({ shopId: "one", idempotencyKey: "lease", eventType: "payment_failed", payload: {}, recipientType: "customer", recipientEmail: null }); job.status = "processing"; job.leaseExpiresAt = new Date("2026-08-21T11:00:00Z"); await f.service.run(); assert.equal(job.status, "missing_recipient"); assert.equal(f.sends, 0); });
test("429 and 5xx retry finitely while permanent errors terminate", async () => { for (const [statusCode, expected] of [[429, "retry"], [503, "retry"], [422, "permanent_failure"]] as const) { const f = outboxFixture({ error: { message: "provider", statusCode } }); const job: any = await f.service.enqueue({ shopId: "one", idempotencyKey: `e${statusCode}`, eventType: "payment_failed", payload: {}, recipientType: "team", recipientEmail: "team@example.com" }); await f.service.run(); assert.equal(job.status, expected); } });
test("Resend webhook requires signature and deduplicates delivery events", async () => { process.env.RESEND_WEBHOOK_SECRET = "whsec_test"; const events = new Map<string, any>(), job = { id: "j1", shopId: "one", status: "sent" }; const db: any = { notificationDeliveryEvent: { findUnique: async ({ where }: any) => events.get(where.providerEventId), create: async ({ data }: any) => { events.set(data.providerEventId, data); } }, notificationOutbox: { findUnique: async () => job, update: async ({ data }: any) => Object.assign(job, data) }, $transaction: async (fn: any) => fn(db) }; const provider: any = { webhooks: { verify: () => ({ id: "evt1", type: "email.delivered", created_at: "2026-08-21T12:00:00Z", data: { email_id: "email1" } }) } }; const service = new ResendWebhookService(db, provider, {} as any); await assert.rejects(service.handle("{}", {}), /invalid_signature/); assert.deepEqual(await service.handle("{}", { id: "evt1", timestamp: "1", signature: "sig" }), { processed: true }); assert.equal(job.status, "delivered"); assert.deepEqual(await service.handle("{}", { id: "evt1", timestamp: "1", signature: "sig" }), { duplicate: true }); });
test("Resend webhook maps bounced complained and suppressed terminal states", async () => { process.env.RESEND_WEBHOOK_SECRET = "whsec_test"; for (const type of ["email.bounced", "email.complained", "email.suppressed"]) { const job: any = { id: type, shopId: "one", status: "sent" }, db: any = { notificationDeliveryEvent: { findUnique: async () => null, create: async () => ({}) }, notificationOutbox: { findUnique: async () => job, update: async ({ data }: any) => Object.assign(job, data) }, $transaction: async (fn: any) => fn(db) }, provider: any = { webhooks: { verify: () => ({ id: `evt-${type}`, type, data: { email_id: type } }) } }; await new ResendWebhookService(db, provider, {} as any).handle("{}", { id: `evt-${type}`, timestamp: "1", signature: "sig" }); assert.equal(job.status, type.slice(6)); } });
