import assert from "node:assert/strict";
import test from "node:test";
import { TeamNotificationFrequency } from "@prisma/client";
import { NotificationEventService } from "../NotificationEventService";

test("global and individual toggles suppress customer and team notification production", async () => { let enqueued = 0; const db = { notificationSettings: { findUnique: async () => ({ customerNotificationsEnabled: false, paymentFailedEnabled: false, teamFrequency: TeamNotificationFrequency.IMMEDIATELY, teamEmails: ["team@example.com"] }) } }, outbox = { enqueue: async () => { enqueued++; } }, service = new NotificationEventService(db as never, outbox as never); assert.deepEqual(await service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "attempt", payload: {}, customerEmail: "customer@example.com" }), { customer: 0, team: 0 }); assert.equal(enqueued, 0); });

test("customer recipient is never replaced by a team address", async () => { const recipients: string[] = [], db = { notificationSettings: { findUnique: async () => ({ customerNotificationsEnabled: true, paymentFailedEnabled: true, teamFrequency: TeamNotificationFrequency.IMMEDIATELY, teamEmails: ["team@example.com"] }) } }, outbox = { enqueue: async (input: { recipientEmail?: string | null }) => { recipients.push(String(input.recipientEmail)); } }, service = new NotificationEventService(db as never, outbox as never); await service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "attempt", payload: {}, customerEmail: "customer@example.com" }); assert.deepEqual(recipients, ["customer@example.com", "team@example.com"]); });

test("DAILY summary concurrency creates one delivery per recipient and records all included events", async () => { const now = new Date("2026-08-22T03:01:00Z"), events: any[] = [{ id: "e1", shopId: "one", frequency: TeamNotificationFrequency.DAILY_SUMMARY, windowKey: "DAILY_SUMMARY:2026-08-21T03:00:00.000Z", windowEndAt: new Date("2026-08-22T03:00:00Z"), includedInOutboxId: null, eventType: "payment_failed", payload: {}, createdAt: new Date(1) }, { id: "e2", shopId: "one", frequency: TeamNotificationFrequency.DAILY_SUMMARY, windowKey: "DAILY_SUMMARY:2026-08-21T03:00:00.000Z", windowEndAt: new Date("2026-08-22T03:00:00Z"), includedInOutboxId: null, eventType: "retry_scheduled", payload: {}, createdAt: new Date(2) }], deliveries = new Map<string, any>(); const db: any = { notificationEvent: { findMany: async ({ select }: any) => select ? [{ shopId: "one", frequency: TeamNotificationFrequency.DAILY_SUMMARY, windowKey: events[0].windowKey }] : events.filter(event => !event.includedInOutboxId), updateMany: async ({ data }: any) => { for (const event of events) if (!event.includedInOutboxId) event.includedInOutboxId = data.includedInOutboxId; return { count: events.length }; } }, notificationSettings: { findUnique: async () => ({ teamFrequency: TeamNotificationFrequency.DAILY_SUMMARY, teamEmails: ["a@example.com", "b@example.com"] }) }, notificationOutbox: { upsert: async ({ where, create }: any) => { if (!deliveries.has(where.idempotencyKey)) deliveries.set(where.idempotencyKey, { id: `o${deliveries.size + 1}`, ...create }); return deliveries.get(where.idempotencyKey); } }, $transaction: async (fn: any) => fn(db) }, service = new NotificationEventService(db, {} as never); await Promise.all([service.materializeSummaries(20, now), service.materializeSummaries(20, now)]); assert.equal(deliveries.size, 2); for (const delivery of deliveries.values()) assert.deepEqual(delivery.includedEventIds, ["e1", "e2"]); assert.equal(events.every(event => event.includedInOutboxId), true); });

test("WEEKLY and NEVER do not lose or incorrectly deliver events", async () => { let enqueued = 0, stored = 0; const settings: { customerNotificationsEnabled: boolean; paymentFailedEnabled: boolean; teamFrequency: TeamNotificationFrequency; teamEmails: string[] } = { customerNotificationsEnabled: false, paymentFailedEnabled: true, teamFrequency: TeamNotificationFrequency.NEVER, teamEmails: ["team@example.com"] }, db: any = { notificationSettings: { findUnique: async () => settings }, notificationEvent: { upsert: async () => { stored++; } } }, service = new NotificationEventService(db, { enqueue: async () => { enqueued++; } } as never); await service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "never", payload: {} }); assert.equal(enqueued, 0); assert.equal(stored, 0); settings.teamFrequency = TeamNotificationFrequency.WEEKLY_SUMMARY; await service.emit({ shopId: "one", eventType: "payment_failed", sourceKey: "weekly", payload: {} }); assert.equal(stored, 1); });
