import assert from "node:assert/strict";
import test from "node:test";
import { RetryCronController } from "../RetryCronController";

function response() { const state = { status: 200, body: undefined as unknown }; return { state, value: { status(code: number) { state.status = code; return this; }, json(body: unknown) { state.body = body; return this; } } }; }
function request(secret?: string) { return { headers: { authorization: secret ? `Bearer ${secret}` : undefined }, query: {} }; }

test("scheduled cron requires CRON_SECRET and runs producers before the outbox", async () => { process.env.CRON_SECRET = "cron-test"; const calls: string[] = [], controller = new RetryCronController({ run: async () => { calls.push("retry"); return { claimed: 1 }; } } as never, { run: async () => { calls.push("outbox"); return { sent: 2 }; } } as never, { runCredentialCleanup: async () => { calls.push("cleanup"); return { revoked: 1 }; } } as never, { materializeSummaries: async () => { calls.push("summaries"); return { created: 1 }; } } as never); const unauthorized = response(); await controller.run(request() as never, unauthorized.value as never); assert.equal(unauthorized.state.status, 401); const output = response(); await controller.run(request("cron-test") as never, output.value as never); assert.equal(output.state.status, 200); assert.deepEqual(calls, ["retry", "summaries", "outbox", "cleanup"]); assert.equal((output.state.body as { success: boolean }).success, true); });

test("partial cron failure is explicit and does not hide successful notification drain", async () => { process.env.CRON_SECRET = "cron-test"; let notificationRuns = 0; const controller = new RetryCronController({ run: async () => { throw new Error("retry failed"); } } as never, { run: async () => { notificationRuns++; return { sent: 1 }; } } as never, { runCredentialCleanup: async () => ({ revoked: 0 }) } as never, { materializeSummaries: async () => ({ created: 0 }) } as never); const output = response(); await controller.run(request("cron-test") as never, output.value as never); assert.equal(output.state.status, 500); assert.equal(notificationRuns, 1); const body = output.state.body as { success: boolean; retry: { success: boolean }; notifications: { success: boolean } }; assert.equal(body.success, false); assert.equal(body.retry.success, false); assert.equal(body.notifications.success, true); });

test("concurrent and repeated cron calls delegate idempotency to independently claimed workers", async () => { process.env.CRON_SECRET = "cron-test"; let retryCalls = 0, notificationCalls = 0; const controller = new RetryCronController({ run: async () => ({ run: ++retryCalls }) } as never, { run: async () => ({ run: ++notificationCalls }) } as never, { runCredentialCleanup: async () => ({}) } as never, { materializeSummaries: async () => ({}) } as never); const responses = [response(), response()]; await Promise.all(responses.map(output => controller.run(request("cron-test") as never, output.value as never))); assert.equal(retryCalls, 2); assert.equal(notificationCalls, 2); assert.equal(responses.every(output => output.state.status === 200), true); });

test("a real notification event produced by retry is drained in the same cron invocation", async () => { process.env.CRON_SECRET = "cron-test"; const durableOutbox: string[] = [], sent: string[] = [], controller = new RetryCronController({ run: async () => { durableOutbox.push("retry-payment-failed"); return { completed: 1 }; } } as never, { run: async () => { sent.push(...durableOutbox.splice(0)); return { sent: sent.length }; } } as never, { runCredentialCleanup: async () => ({}) } as never, { materializeSummaries: async () => ({ created: 0 }) } as never), output = response(); await controller.run(request("cron-test") as never, output.value as never); assert.deepEqual(sent, ["retry-payment-failed"]); assert.equal(durableOutbox.length, 0); });
